version: '3.9'
services:

  django-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      meilisearch:
        condition: service_healthy




  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms
    environment:
      - MEILI_DB_PATH=/data.ms
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 10s
      timeout: 5s
      retries: 5


